Repository nbc-react-3rd-final-project-a5/yolocean, pull requests merged in 2024-01, with the labels that each got.

#8 [feat/image] drag&drop 기능 및 업로드 기능
  src/app/api/storage/route.ts
  src/app/image/page.tsx
  src/components/DragDropImageInput.tsx
  src/hooks/index.ts
  src/hooks/useImageFile.ts
Labels: 🎉 add, ✨ update

#9 [feat/payment] portone sdk 를 이용한 인증 및 결제
  src/app/layout.tsx
  src/lib/Portone.tsx
Labels: 🎉 add

#10 [Feat/login] 로그인/회원가입 구현 (#1)
  package-lock.json
  package.json
  public/images/google_login.png
  public/images/kakao_login.png
  src/app/auth/SignIn.tsx
  src/app/auth/SignUp.tsx
  src/app/auth/page.tsx
Labels: 🎉 add, ✨ update, 🩹 fix, 🔨script

#12 [feat/payment] 테스트 결제 인증 구현 (#11)
  src/app/globals.css
  src/lib/Portone.tsx
Labels: ✨ update

#14 [feat/product] 상품페이지 조회기능 #5
  src/app/api/product/[productId]/route.ts
  src/app/api/product/route.ts
  src/app/layout.tsx
  src/app/product/[productId]/page.tsx
  src/app/product/page.tsx
  src/components/Modal.tsx
  src/hooks/useProduct.tsx
  src/lib/KakaoMap.tsx
  src/types/db.ts
  src/types/supabase.ts
  yarn.lock
Labels: 🎉 add, ✨ update

#17 [feat/avatar] rounded 이미지 컴포넌트 (#16)
  src/components/Avatar.tsx
Labels: 🎉 add

#20 Feat/modal portal을 사용하여 swal같은 모달 만들기
  src/app/layout.tsx
  src/app/product/[productId]/page.tsx
  src/app/product/page.tsx
  src/components/Modal.tsx
  src/components/portal/CreateAlert.tsx
  src/components/portal/CreateModal.tsx
  src/lib/KakaoMap.tsx
  src/store/alertStore.ts
  src/store/modalStore.ts
  yarn.lock
Labels: 🎉 add, ✨ update

#21 Feat/tab Tab컴포넌트 생성
  src/app/product/page.tsx
  src/components/Tab.tsx
Labels: 🎉 add

#25 [feat/form] Product 등록 페이지 구현
  package-lock.json
  package.json
  src/app/admin/product/page.tsx
  src/app/admin/store/PostCode.tsx
  src/app/admin/store/page.tsx
  src/app/admin/store/useMap.ts
  src/app/api/category/route.ts
  src/app/api/product/route.ts
  src/app/api/storage/route.ts
  src/app/api/store/route.ts
  src/app/layout.tsx
  src/store/address.ts
  src/types/supabase.ts
  tsconfig.json
Labels: 🎉 add, ✨ update, 🔨script

#30 Feat/input 재사용가능한 input 컴포넌트 생성
  src/app/layout.tsx
  src/app/product/page.tsx
  src/components/ContextInput.tsx
  src/components/Input.tsx
Labels: 🎉 add

#31 [Feat/form] Product 등록 페이지 수정 & Store 등록 페이지 추가
  src/app/admin/product/page.tsx
  src/app/admin/store/PostCode.tsx
  src/app/admin/store/page.tsx
  src/app/admin/store/useMap.ts
  src/app/api/region/route.ts
  src/app/api/store/route.ts
  src/app/layout.tsx
  src/hooks/useCategory.tsx
  src/hooks/useImageFile.ts
  src/hooks/useRegion.ts
  src/store/addressStore.ts
  src/types/db.ts
  src/types/supabase.ts
Labels: 🎉 add, ✨ update, 🩹 fix, 💄 style

#33 [Feat/form] Store 등록 페이지 버그 fix
  src/app/admin/product/page.tsx
  src/app/admin/store/PostCode.tsx
  src/app/admin/store/page.tsx
  src/store/addressStore.ts
  src/types/db.ts
Labels: 🐛 bugfix, 🔥 del

#32 Feat/modal confirm생성컴포넌트 생성 및 모달 오류 수정
  src/app/layout.tsx
  src/app/product/page.tsx
  src/components/portal/CreateAlert.tsx
  src/components/portal/CreateConfirm.tsx
  src/components/portal/CreateModal.tsx
  src/hooks/useCategory.ts
  src/hooks/useProduct.ts
  src/store/alertStore.ts
  src/store/confirmStore.ts
  src/types/supabase.ts
Labels: 🎉 add, ✨ update, 🩹 fix

#35 [Feat/form] Product 등록 페이지 할인률 추가
  src/app/admin/product/page.tsx
  src/app/category/[categoryId]/CategorySection.tsx
  src/app/category/[categoryId]/page.tsx
Labels: ✨ update

#36 Feat/product 코드벤션에 맞춰 수정 및 테스트코드 삭제
  src/app/api/product/route.ts
  src/app/product/[productId]/page.tsx
  src/app/product/page.tsx
  src/components/Card.tsx
  src/components/ContextInput.tsx
  src/components/Input.tsx
  src/components/Tab.tsx
  src/components/portal/CreateConfirm.tsx
Labels: 🩹 fix, 🔥 del

#37 Feat/modal firx: section컴포넌트 props수정, hooks함수들 index에서 expoert하고 import하도록 수정
  src/app/admin/product/page.tsx
  src/app/admin/store/page.tsx
  src/app/product/[productId]/page.tsx
  src/app/product/page.tsx
  src/components/DragDropImageInput.tsx
  src/components/Inputcopy.tsx
  src/components/category/HeadCategory.tsx
  src/components/layout/Section.tsx
  src/components/portal/CreateModal.tsx
  src/hooks/index.ts
  src/store/modalStore.ts
Labels: 🩹 fix

#38 add:Accordion컴포넌트 생성 , 고객센터 faq페이지 생성(customer)
  src/app/customer/page.tsx
  src/app/product/[productId]/page.tsx
  src/components/Accordion.tsx
  src/components/Tab.tsx
  src/data/customerData.json
  src/service/faq.ts
Labels: feat

#39 [feat/form] 리뷰 qna form
  src/app/admin/product/page.tsx
  src/app/api/review/[userId]/route.ts
  src/app/image/page.tsx
  src/app/qna/[productId]/page.tsx
  src/app/qna/page.tsx
  src/app/review/[productId]/page.tsx
  src/components/InputImage.tsx
  src/components/InputImageView.tsx
  src/components/form/ReviewForm.tsx
  src/components/layout/Section.tsx
  src/hooks/index.ts
  src/hooks/useImageFile.ts
  src/hooks/useImageInput.ts
  src/types/form.ts
  src/utils/getPath.ts
  src/utils/useStorage.ts
Labels: feat, refact

#43 Feat/product 상품상세페이지의 조작가능한 부분을 다듬었습니다.
  package-lock.json
  package.json
  src/app/customer/page.tsx
  src/app/globals.css
  src/app/product/[productId]/Controller.tsx
  src/app/product/[productId]/Info.tsx
  src/app/product/[productId]/page.tsx
  src/components/NumberInput.tsx
  src/components/Tab.tsx
Labels: feat, style

#42 [Feat/category] 카테고리 페이지 지점 선택 모달 추가 (#34)
  .github/ISSUE_TEMPLATE/이슈-생성.md
  src/app/admin/product/page.tsx
  src/app/admin/store/page.tsx
  src/app/api/category/[categoryId]/route.ts
  src/app/category/[categoryId]/CategoryHeader.tsx
  src/app/category/[categoryId]/CategorySection.tsx
  src/app/category/[categoryId]/SelectOffice.tsx
  src/app/category/[categoryId]/page.tsx
  src/components/category/HeadCategory.tsx
  src/components/portal/CreateModal.tsx
  src/hooks/index.ts
  src/hooks/useCategory.ts
  src/hooks/useRegion.ts
  src/store/officeStore.ts
  src/types/supabase.ts
Labels: feat

#52 [Feat/user] Region id 전역상태관리
  src/app/admin/product/page.tsx
  src/app/category/[categoryId]/SelectOffice.tsx
  src/store/officeStore.ts
Labels: feat

#47 Feat/product 상품페이지 삭제, 상품상세정보페이지 category페이지 하위페이지로이동
  src/app/category/[categoryId]/[productId]/Controller.tsx
  src/app/category/[categoryId]/[productId]/Info.tsx
  src/app/category/[categoryId]/[productId]/page.tsx
  src/app/customer/page.tsx
  src/app/product/page.tsx
  src/components/NumberInput.tsx
  src/components/Tab.tsx
Labels: fix, style

#50 [feat/layout] main 스타일지정 (#44)
  src/app/layout.tsx
  src/components/layout/Footer.tsx
Labels: style

#53 [feat/user] 유저정보 수정 및 로그인 유저 정보 가져오기 (#49)
  src/app/api/users/[userId]/route.ts
  src/app/api/users/route.ts
  src/app/users/[userId]/EditUserInfo.tsx
  src/app/users/[userId]/UserInfo.tsx
  src/app/users/[userId]/UserInfoSection.tsx
  src/app/users/[userId]/page.tsx
  src/hooks/index.ts
  src/hooks/useAuth.ts
  src/store/authStore.ts
  src/store/editUserStore.ts
Labels: feat

#56 Feat/product
  src/app/api/store/[regionId]/route.ts
  src/app/api/store/route.ts
  src/app/category/[categoryId]/[productId]/ControlForm.tsx
  src/app/category/[categoryId]/[productId]/Controller.tsx
  src/app/category/[categoryId]/[productId]/Info.tsx
  src/app/category/[categoryId]/[productId]/StockTable.tsx
  src/app/category/[categoryId]/[productId]/page.tsx
  src/app/customer/page.tsx
  src/app/globals.css
  src/components/NumberInput.tsx
  src/components/Tab.tsx
  src/hooks/useOffice.ts
  src/lib/KakaoMap.tsx
  src/types/db.ts
Labels: style

#55 [feat/cart] 장바구니 삭제/수량 변경 기능 구현 (#27)
  src/app/api/cart/[id]/route.ts
  src/app/api/cart/route.ts
  src/app/auth/SignIn.tsx
  src/app/auth/SignUp.tsx
  src/app/cart/CartItem.tsx
  src/app/cart/page.tsx
  src/app/payment/page.tsx
  src/app/product/[productId]/Controller.tsx
  src/app/product/[productId]/Info.tsx
  src/hooks/index.ts
  src/hooks/useCart.ts
Labels: feat

#57 style:전역스타일 추가 및 tailwiconfig 기본테마 수정
  src/app/globals.css
  tailwind.config.ts
Labels: style

#58 [Feat/user] Avatar 컴포넌트 스타일 수정 & null 이미지 추가, user 프로필 수정 기능 구현 중 (#49)
  public/images/avatar_default.jpg
  src/app/users/[userId]/EditUserInfo.tsx
  src/app/users/[userId]/UserInfo.tsx
  src/app/users/[userId]/UserInfoSection.tsx
  src/components/Avatar.tsx
  src/components/auth/AuthBtn.tsx
Labels: feat, style

#60 [feat/review] 리뷰 관련
  src/app/api/review/[userId]/route.ts
  src/app/api/review/products/[productId]/route.ts
  src/app/api/review/route.ts
  src/app/api/review/users/[userId]/[reviewId]/route.ts
  src/app/api/review/users/[userId]/route.ts
  src/app/api/storage/route.ts
  src/app/review/[productId]/page.tsx
  src/app/review/form/error.tsx
  src/app/review/form/page.tsx
  src/app/review/productReviewList/page.tsx
  src/app/review/userReviewList/page.tsx
  src/components/InputImageView.tsx
  src/components/form/ReviewForm.tsx
  src/components/review/ProductReviewList.tsx
  src/components/review/ReviewBtnGroup.tsx
  src/components/review/ReviewItem.tsx
  src/components/review/ReviewList.tsx
  src/hooks/index.ts
  src/hooks/useImageInput.ts
  src/hooks/useReview.ts
  src/types/db.ts
  src/types/form.ts
  src/types/supabase.ts
  src/utils/convertTime.ts
  src/utils/useStorage.ts
Labels: feat, fix, refact, style, chore

#61 [feat/layout] footer 컴포넌트 style 변경
  src/components/layout/Footer.tsx
Labels: style

#65 [Feat/user] 프로필 사진 수정 기능 구현
  src/app/users/[userId]/EditUserInfo.tsx
  src/app/users/[userId]/UserInfo.tsx
  src/app/users/[userId]/UserInfoSection.tsx
Labels: feat

#66 [feat/header] 헤더 스타일링 (#15)
  src/app/cart/page.tsx
  src/components/auth/AuthBtn.tsx
  src/components/category/HeadCategory.tsx
  src/components/layout/Header.tsx
Labels: style

#67 [Feat/user] 프로필 수정 기능 완성, AuthChange 컴포넌트 layout 폴더로 이동
  src/app/layout.tsx
  src/app/users/[userId]/EditUserInfo.tsx
  src/components/layout/AuthChage.tsx
Labels: feat

#70 [feat/layout] 헤더 style 추가
  src/components/layout/Header.tsx
Labels: style

#71 [feat/user] 마이페이지 프로필 스타일 추가
  src/app/cart/page.tsx
  src/app/users/[userId]/EditUserInfo.tsx
  src/app/users/[userId]/UserInfo.tsx
  src/app/users/[userId]/page.tsx
Labels: style

#69 [Feat/cart] 비로그인 시 장바구니 처리 (#27)
  src/app/cart/CartItem.tsx
  src/app/cart/page.tsx
  src/app/category/[categoryId]/[productId]/ControlForm.tsx
Labels: feat

#73 [feat/user] 마이페이지 프로필 스타일 수정, BreadCrumb 스타일 수정
  src/app/users/[userId]/EditUserInfo.tsx
  src/components/layout/PageBreadCrumb.tsx
Labels: style

#74 [feat/category] 카테고리페이지 상단 스타일 수정(#34)
  src/app/category/[categoryId]/CategoryHeader.tsx
Labels: style

#76 [feat/main] 메인페이지 컴포넌트 작성
  src/app/category/[categoryId]/CategorySection.tsx
  src/app/page.tsx
  src/components/CardLists.tsx
Labels: feat, refact

#77 [feat/layout] 한영 font 추가
  src/app/layout.tsx
  src/app/styles/fonts/PretendardVariable.woff2
  src/app/styles/fonts/REM-VariableFont_wght.ttf
  src/app/styles/fonts/fonts.module.css
  src/app/styles/fonts/fonts.ts
Labels: style

#78 Feat/product 클립보드 복사기능 추가 , Tab상단 고정 및 현재 보고있는 탭에따라 active시키도록 수정
  src/app/api/product/[productId]/route.ts
  src/app/category/[categoryId]/CategorySection.tsx
  src/app/category/[categoryId]/[productId]/Info.tsx
  src/app/category/[categoryId]/[productId]/ShareModal.tsx
  src/app/category/[categoryId]/[productId]/page.tsx
  src/components/Tab.tsx
  src/hooks/useReview.ts
Labels: feat, style

#79 [Feat/cart] 결제페이지 할인금액 적용/스타일링
  src/app/cart/CartItem.tsx
  src/app/cart/page.tsx
  src/app/payment/page.tsx
Labels: feat, fix, style

#82 Feat/product 상품상세페이지 Tab오류 수정 및 카드컴포넌트 css깨짐 수정
  src/app/api/qna/[productId]/route.ts
  src/app/category/[categoryId]/[productId]/Info.tsx
  src/components/Card.tsx
  src/components/layout/AuthChage.tsx
  src/components/review/ReviewItem.tsx
  src/hooks/useReview.ts
Labels: feat

#80 [feat/main] 메인컴포넌트 작업중 & category useQuery 수정
  src/app/admin/product/page.tsx
  src/app/api/review/route.ts
  src/app/page.tsx
  src/hooks/index.ts
  src/hooks/useCategory.ts
  src/types/db.ts
Labels: feat, refact, style

#83 [feat/category] 주소 선택시에만 아이콘 렌더링 (#34)
  src/app/category/[categoryId]/CategoryHeader.tsx
Labels: fix

#84 feat,style: 회원가입 시 전화번호 입력 및 auth페이지 스타일링 (#81)
  src/app/auth/SignIn.tsx
  src/app/auth/SignUp.tsx
  src/app/auth/page.tsx
  src/components/layout/Header.tsx
  src/types/supabase.ts
Labels: feat, fix, style

#88 [feat/main] 헤더 검색 부분 컴포넌트 분리 & 검색 페이지 구현
  src/app/search/[searchWord]/page.tsx
  src/app/search/page.tsx
  src/components/Card.tsx
  src/components/layout/Header.tsx
  src/components/layout/HeaderSearch.tsx
  src/store/searchStore.ts
Labels: feat

#89 [feat/find] 아이디 찾기 (본인인증 제외)
  src/app/auth/SignIn.tsx
  src/app/auth/SignUp.tsx
  src/app/auth/[find]/FindID.tsx
  src/app/auth/[find]/FindPW.tsx
  src/app/auth/[find]/ResultID.tsx
  src/app/auth/[find]/ResultPW.tsx
  src/app/auth/[find]/page.tsx
Labels: feat, style

#90 [feat/layout] 페이지 컨트롤 버튼 생성
  src/app/layout.tsx
  src/components/layout/Footer.tsx
  src/components/layout/PageControlBtnGroup.tsx
  src/data/footerData.json
Labels: feat, refact, style

#91 [Feat/find] pw 재설정
  src/app/auth/[find]/FindID.tsx
  src/app/auth/[find]/FindPW.tsx
  src/app/auth/[find]/ResultPW.tsx
  src/service/supabase.ts
Labels: feat, fix, style

#87 [feat/payment] 핸드폰 인증 및 결제 기능
  src/app/api/auth/route.ts
  src/app/auth/SignUp.tsx
  src/app/auth/[find]/FindID.tsx
  src/app/auth/[find]/FindPW.tsx
  src/app/auth/[find]/ResultPW.tsx
  src/app/payment/page.tsx
  src/app/test/page.tsx
  src/lib/Portone.tsx
  src/lib/portone.ts
Labels: feat, fix, style

#92 feat:pagenation컴포넌트 Link로 수정 , 페이지네이션 (Qna만 완료 )
  src/app/api/products/[categoryId]/route.ts
  src/app/api/qna/product/[productId]/route.ts
  src/app/api/review/products/[productId]/route.ts
  src/app/category/[categoryId]/[productId]/(article)/Description.tsx
  src/app/category/[categoryId]/[productId]/(article)/Infomation.tsx
  src/app/category/[categoryId]/[productId]/(article)/Qna.tsx
  src/app/category/[categoryId]/[productId]/(article)/Review.tsx
  src/app/category/[categoryId]/[productId]/CommonGuide.tsx
  src/app/category/[categoryId]/[productId]/Info.tsx
  src/app/category/[categoryId]/[productId]/page.tsx
  src/components/Pagenation.tsx
Labels: feat, fix

#94 Feat/product pagenation 클라이언트컴포넌트로 수정
  src/app/api/review/products/[productId]/route.ts
  src/app/category/[categoryId]/CategorySection.tsx
  src/app/category/[categoryId]/[productId]/(article)/Qna.tsx
  src/app/category/[categoryId]/[productId]/(article)/Review.tsx
  src/app/category/[categoryId]/[productId]/ControlForm.tsx
  src/app/category/[categoryId]/[productId]/Info.tsx
  src/app/page.tsx
  src/components/Card.tsx
  src/components/Pagenation.tsx
Labels: fix

#95 [Feat/main] supabase 타입 수정
  src/app/page.tsx
  src/types/supabase.ts
Labels: fix

#98 main 페이지 리뷰 작업
  src/app/api/review/fixed/route.ts
  src/app/page.tsx
  src/types/db.ts
Labels: fix

#102 [feat/mypage] 마이페이지 기능 추가
  src/app/api/rent/[userId]/route.ts
  src/app/users/[userId]/(tabContent)/RentItem.tsx
  src/app/users/[userId]/(tabContent)/UserQnaList.tsx
  src/app/users/[userId]/(tabContent)/UserRentList.tsx
  src/app/users/[userId]/(tabContent)/UserReservationList.tsx
  src/app/users/[userId]/(tabContent)/UserReviewList.tsx
  src/app/users/[userId]/EditUserInfo.tsx
  src/app/users/[userId]/UserTab.tsx
  src/app/users/[userId]/page.tsx
Labels: feat, fix

#105 [refact/admin] : admin 페이지, 헤더 카테고리 수정완료
  src/app/admin/product/page.tsx
  src/app/admin/store/page.tsx
  src/app/api/review/fixed/route.ts
  src/app/auth/SignIn.tsx
  src/app/auth/SignUp.tsx
  src/app/auth/[find]/FindID.tsx
  src/app/auth/[find]/FindPW.tsx
  src/app/category/[categoryId]/CategoryHeader.tsx
  src/app/category/[categoryId]/page.tsx
  src/app/page.tsx
  src/app/search/[searchWord]/page.tsx
  src/components/category/HeadCategory.tsx
  src/service/table/category.ts
  src/service/table/region.ts
  src/service/table/store.ts
Labels: refact

#106 [refact/cart] 장바구니, 결제 페이지 수정 완료
  src/app/auth/SignIn.tsx
  src/app/cart/CartItem.tsx
  src/app/cart/[userId]/page.tsx
  src/app/payment/[userId]/page.tsx
  src/legacyHook/useCart.ts
  src/middleware.ts
Labels: refact

#107 [refact/api] 결제 시 rent 테이블에 반영 수정
  src/app/payment/[userId]/page.tsx
Labels: refact

#108 [refact/cart] mutation 함수 수정
  src/app/cart/CartItem.tsx
  src/app/cart/[userId]/page.tsx
  src/app/payment/[userId]/page.tsx
  src/hook/useCustomMutation.ts
Labels: refact

#113 [refact/api] qna 및 리뷰 form 정리
  src/app/api/user/[userId]/qna/[qnaId]/route.ts
  src/app/api/user/[userId]/qna/route.ts
  src/app/category/[categoryId]/[productId]/Info.tsx
  src/app/form/(form)/QnaForm.tsx
  src/app/form/(form)/ReviewForm.tsx
  src/app/form/FormSwitch.tsx
  src/app/form/ProductInfo.tsx
  src/app/form/page.tsx
  src/app/page.tsx
  src/app/product/[productId]/(article)/Description.tsx
  src/app/product/[productId]/(article)/Infomation.tsx
  src/app/product/[productId]/(article)/Qna.tsx
  src/app/product/[productId]/(article)/Review.tsx
  src/app/product/[productId]/CommonGuide.tsx
  src/app/product/[productId]/ControlForm.tsx
  src/app/product/[productId]/Info.tsx
  src/app/product/[productId]/ShareModal.tsx
  src/app/product/[productId]/StockTable.tsx
  src/app/product/[productId]/page.tsx
  src/app/qna/[qnaId]/QnaForm.tsx
  src/app/users/[userId]/UserTab.tsx
  src/app/users/[userId]/page.tsx
  src/components/Card.tsx
  src/components/DragDropImageInput.tsx
  src/components/Pagenation.tsx
  src/components/Tab.tsx
  src/components/form/FormFieldSet.tsx
  src/components/form/ReviewForm.tsx
  src/service/table/qna.ts
  src/service/table/review.ts
  src/types/db.ts
Labels: fix, refact

#116 [feat/storage] banner 데이터 가져오기
  src/app/api/product/[productId]/route.ts
  src/app/api/storage/banner/[bannerName]/route.ts
  src/app/product/[productId]/(article)/Qna.tsx
  src/app/product/[productId]/View.tsx
  src/app/product/[productId]/page.tsx
  src/app/users/[userId]/(tabContent)/RentItem.tsx
  src/app/users/[userId]/(tabContent)/UserQnaList.tsx
  src/app/users/[userId]/(tabContent)/UserRentList.tsx
  src/app/users/[userId]/(tabContent)/UserReservationList.tsx
  src/app/users/[userId]/UserInfoSection.tsx
  src/app/users/[userId]/UserTab.tsx
  src/app/users/[userId]/page.tsx
  src/components/review/ReviewBtnGroup.tsx
  src/service/table/banner.ts
  src/service/table/product.ts
Labels: feat

#117 Feat/swiper 캐러셀 만들었습니다.
  package-lock.json
  package.json
  src/app/api/storage/carousel/route.ts
  src/app/page.tsx
  src/app/swiper.css
  src/components/Carousel.tsx
  src/lib/SwiperBox.tsx
  src/middleware.ts
  src/service/table/carousel.ts
  src/service/table/index.ts
Labels: feat, style

#118 Feat/pulse 로딩 스피너와 병행해서 사용할 pulse컴포넌트를 제작하였습니다.
  src/app/category/[categoryId]/page.tsx
  src/app/page.tsx
  src/app/product/[productId]/(article)/Review.tsx
  src/components/Carousel.tsx
  src/components/pulse/AvatarPulse.tsx
  src/components/pulse/CardPulse.tsx
  src/components/pulse/ImgPulse.tsx
  src/components/pulse/ReviewPulse.tsx
Labels: feat

#115 Feat/middleware 미들웨어를 통해 로그인한 사용자의 토큰을 검사하도록 작업중.
  src/app/product/[productId]/View.tsx
  src/middleware.ts
Labels: feat

#120 style: dropdown 스타일링
  src/app/cart/CartItem.tsx
  src/app/cart/[userId]/page.tsx
  src/components/auth/AuthBtn.tsx
  src/components/category/HeadCategory.tsx
  src/middleware.ts
Labels: style

#119 [feat/spiner] spinner
  src/app/styles/spinner.module.css
  src/components/Spinner.tsx
Labels: feat, style

#125 [style/header] 모바일 헤더 스타일링
  src/app/users/[userId]/EditUserInfo.tsx
  src/components/auth/AuthBtn.tsx
  src/components/category/HeadCategory.tsx
  src/components/layout/Header.tsx
  src/components/layout/HeaderSearch.tsx
  src/components/layout/mobile/MobileHeader.tsx
  src/components/layout/mobile/MobileSearch.tsx
Labels: style

#126 [feat/button] 커스텀 버튼 및 링크
  src/components/CustomButton.tsx
  src/components/CustomLink.tsx
Labels: feat

#127 Style/product 상세페이지 , 카테고리 페이지 , 모달, 모바일css 적용
  src/app/category/[categoryId]/CategorySection.tsx
  src/app/category/[categoryId]/SelectOffice.tsx
  src/app/product/[productId]/(article)/Description.tsx
  src/app/product/[productId]/(article)/Empty.tsx
  src/app/product/[productId]/(article)/Qna.tsx
  src/app/product/[productId]/(article)/Review.tsx
  src/app/product/[productId]/ControlForm.tsx
  src/app/product/[productId]/Info.tsx
  src/app/product/[productId]/ShareModal.tsx
  src/app/product/[productId]/View.tsx
  src/app/product/[productId]/page.tsx
  src/components/Card.tsx
  src/components/CardLists.tsx
  src/components/Carousel.tsx
  src/components/CustomButton.tsx
  src/components/Tab.tsx
  src/components/category/HeadCategory.tsx
  src/components/portal/CreateConfirm.tsx
  src/components/portal/CreateModal.tsx
  src/components/pulse/CardPulse.tsx
  src/components/pulse/ReviewPulse.tsx
  src/components/review/ReviewItem.tsx
  src/hook/useCustomMutation.ts
  src/service/table/review.ts
Labels: style

#128 [style/main product] 메인페이지 상품 케러셀 제작
  src/app/page.tsx
  src/app/swiper.css
  src/components/Banner.tsx
  src/components/Card.tsx
  src/components/CardCarousel.tsx
  src/components/layout/Section.tsx
Labels: style

#130 [style/mypage] 마이페이지 수정입니다.
  src/app/users/[userId]/(tabContent)/RentItem.tsx
  src/app/users/[userId]/(tabContent)/UserPagenation.tsx
  src/app/users/[userId]/(tabContent)/UserQnaList.tsx
  src/app/users/[userId]/(tabContent)/UserReviewList.tsx
  src/app/users/[userId]/UserInfo.tsx
  src/app/users/[userId]/UserTab.tsx
  src/components/Pagenation.tsx
  src/service/table/qna.ts
  src/service/table/review.ts
Labels: fix, style

#132 [style/main product] 메인페이지 케러셀 수정
  src/app/swiper.css
  src/app/users/[userId]/(tabContent)/UserQnaList.tsx
  src/app/users/[userId]/(tabContent)/UserRentList.tsx
  src/app/users/[userId]/(tabContent)/UserReservationList.tsx
  src/app/users/[userId]/EditUserInfo.tsx
  src/components/CardCarousel.tsx
  src/components/Carousel.tsx
  src/components/review/ReviewItem.tsx
  tailwind.config.ts
Labels: style

#131 Style/product 테블릿 사이즈로 카드와 상세페이지를 미세 수정했습니다.
  src/app/api/user/[userId]/qna/[qnaId]/route.ts
  src/app/api/user/[userId]/qna/route.ts
  src/app/api/user/[userId]/review/route.ts
  src/app/cart/[userId]/page.tsx
  src/app/category/[categoryId]/CategoryHeader.tsx
  src/app/category/[categoryId]/CategorySection.tsx
  src/app/payment/[userId]/page.tsx
  src/app/product/[productId]/(article)/Qna.tsx
  src/app/product/[productId]/ControlForm.tsx
  src/app/product/[productId]/page.tsx
  src/components/Card.tsx
  src/components/CardLists.tsx
  src/components/layout/HeaderSearch.tsx
  src/components/pulse/CardPulse.tsx
  src/service/table/qna.ts
  src/service/table/review.ts
  tailwind.config.ts
Labels: style

#133 [style/layout]
  src/components/layout/Footer.tsx
  src/components/layout/PageControlBtnGroup.tsx
Labels: style

#134 [style/cartNcus] 모바일 적용 기타 둥둥
  src/app/cart/CartItem.tsx
  src/app/cart/[userId]/page.tsx
  src/app/customer/page.tsx
  src/app/payment/[userId]/page.tsx
  src/app/users/[userId]/UserInfoSection.tsx
  src/components/Tab.tsx
  src/components/category/HeadCategory.tsx
  src/components/pulse/CartPulse.tsx
  src/service/table/cart.ts
Labels: feat, style

#135 [style/category_modal] 위치선택 버튼 반응형 디자인 추가
  src/app/category/[categoryId]/CategoryHeader.tsx
Labels: style

#138 feat:미들웨어 설정 완료
  src/app/customer/page.tsx
  src/middleware.ts
Labels: feat

#136 style: tab 수정(#124)
  src/components/Tab.tsx
Labels: style

#145 [refact/cart]: 약관체크 버튼 수정 및 테스트 결제 명시
  src/app/payment/[userId]/SuccessModal.tsx
  src/app/payment/[userId]/page.tsx
Labels: refact

#144 [feat/main banner] 메인페이지 베너작업 & 리뷰컴포넌트 작업
  src/app/category/[categoryId]/page.tsx
  src/app/opengraph-image.png
  src/app/page.tsx
  src/components/Banner.tsx
  src/service/table/review.ts
Labels: feat, fix

#146 [refact/mypage] 마이페이지 수정내역
  src/app/api/user/[userId]/qna/route.ts
  src/app/api/user/[userId]/rent/route.ts
  src/app/api/user/[userId]/review/route.ts
  src/app/users/[userId]/(tabContent)/UserPagenation.tsx
  src/app/users/[userId]/(tabContent)/UserQnaList.tsx
  src/app/users/[userId]/(tabContent)/UserRentList.tsx
  src/app/users/[userId]/(tabContent)/UserReservationList.tsx
  src/app/users/[userId]/(tabContent)/UserReviewList.tsx
  src/app/users/[userId]/page.tsx
  src/components/Accordion.tsx
  src/components/pulse/UserRentPulse.tsx
  src/components/review/ReviewBtnGroup.tsx
  src/components/review/ReviewItem.tsx
  src/components/review/ReviewList.tsx
  src/service/table/rent.ts
  src/types/db.ts
Labels: fix, refact

#150 [style/search] cart, search 스타일 수정
  src/app/cart/[userId]/page.tsx
  src/app/search/page.tsx
Labels: style

#153 [fix/breadcrumb] breadcrumb 수정
  src/app/auth/SignIn.tsx
  src/app/auth/SignUp.tsx
  src/app/auth/[find]/FindID.tsx
  src/app/auth/[find]/FindPW.tsx
  src/app/category/[categoryId]/CategoryHeader.tsx
  src/app/search/[searchWord]/page.tsx
  src/app/users/[userId]/page.tsx
Labels: fix

#160 [fix/payment] 모바일 회원가입 오류 수정
  src/app/auth/SignUp.tsx
  src/app/auth/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/payment/[userId]/page.tsx
  src/components/layout/PageControlBtnGroup.tsx
  src/lib/portone.ts
Labels: fix

#158 [refact/rent] 렌트 테이블 수정
  src/app/api/user/[userId]/cart/route.ts
  src/app/api/user/[userId]/rent/route.ts
  src/app/payment/[userId]/SuccessModal.tsx
  src/app/payment/[userId]/page.tsx
  src/app/users/[userId]/(tabContent)/RentItem.tsx
  src/types/db.ts
  src/types/supabase.ts
Labels: fix, refact

#164 [fix/payment] 모바일 결제 오류 수정
  src/app/api/certification/payment/route.ts
  src/app/payment/[userId]/page.tsx
  src/lib/portone.ts
Labels: feat, fix, refact

#162 [feat/terms] 결제 페이지 약관 추가
  src/app/page.tsx
  src/app/payment/[userId]/Term.tsx
  src/app/payment/[userId]/page.tsx
  src/data/termData.json
  src/middleware.ts
Labels: feat

#166 [fix/form_button] 취소 버튼 클릭시 뒤로가기
  src/app/form/(form)/QnaForm.tsx
  src/app/form/(form)/ReviewForm.tsx
Labels: fix

#167 fix:category 카테고리 서버컴포넌트로 변경
  src/app/category/[categoryId]/CategorySection.tsx
Labels: fix

#172 [refact/mypage] 마이페이지 서버 컴포넌트로 변환
  src/app/api/user/[userId]/qna/route.ts
  src/app/api/user/[userId]/rent/route.ts
  src/app/api/user/[userId]/review/[reviewId]/route.ts
  src/app/form/(form)/ReviewForm.tsx
  src/app/users/[userId]/(tabContent)/UserQnaList.tsx
  src/app/users/[userId]/(tabContent)/UserRentList.tsx
  src/app/users/[userId]/(tabContent)/UserReservationList.tsx
  src/app/users/[userId]/(tabContent)/UserReviewList.tsx
  src/app/users/[userId]/UserInfo.tsx
  src/app/users/[userId]/UserTab.tsx
  src/app/users/[userId]/page.tsx
  src/components/Pagination.tsx
  src/components/Tab.tsx
  src/service/table/qna.ts
  src/service/table/rent.ts
  src/service/table/review.ts
Labels: fix, refact, style

#170 fix: revalidate추가
  src/app/globals.css
  src/app/product/[productId]/(article)/Qna.tsx
  src/app/product/[productId]/(article)/Revalidate.tsx
  src/app/product/[productId]/(article)/Review.tsx
  src/service/table/qna.ts
  src/service/table/review.ts
Labels: feat

#171 Feat/debounce 단순 시간 수정
  src/app/form/(form)/QnaForm.tsx
  src/app/form/(form)/ReviewForm.tsx
  src/app/product/[productId]/ControlForm.tsx
Labels: fix

#173 [fix/mypage_profile] 마이페이지 프로필 변경 수정
  src/app/users/[userId]/EditUserInfo.tsx
  src/app/users/[userId]/UserInfo.tsx
  src/components/Avatar.tsx
  src/store/editUserStore.ts
Labels: fix
