Repository nbc-react-3rd-final-project-a5/yolocean, pull requests merged in 2024-02, with the labels that each got.

#176 [refact/form] form에 사용되는 useInputImage 리펙토링
  src/app/form/(form)/QnaForm.tsx
  src/app/form/(form)/ReviewForm.tsx
  src/app/users/[userId]/EditUserInfo.tsx
  src/components/DragDropImageInput.tsx
  src/components/InputImage.tsx
  src/components/InputImageView.tsx
  src/hook/useImageInput.ts
  src/utils/vaildateImage.ts
Labels: feat, fix, refact

#175 refact:product 상품상세페이지 및 카테고리 페이지 최적화적용
  src/app/category/[categoryId]/CategoryHeader.tsx
  src/app/category/[categoryId]/CategorySection.tsx
  src/app/category/[categoryId]/SelectOffice.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/page.tsx
  src/app/product/[productId]/(article)/Description.tsx
  src/app/product/[productId]/(article)/Qna.tsx
  src/app/product/[productId]/ControlForm.tsx
  src/app/product/[productId]/Info.tsx
  src/app/product/[productId]/View.tsx
  src/app/product/[productId]/page.tsx
  src/components/Banner.tsx
  src/components/Card.tsx
  src/components/CardCarousel.tsx
  src/components/Carousel.tsx
  src/components/portal/CreateConfirm.tsx
  src/lib/KakaoShare.tsx
Labels: refact

#177 Refact/form 폼작성시 일정시간 스피너가 돌도록 수정
  src/app/form/(form)/QnaForm.tsx
  src/app/form/(form)/ReviewForm.tsx
  src/app/product/[productId]/(article)/Qna.tsx
  src/app/product/[productId]/(article)/Review.tsx
  src/components/Spinner.tsx
Labels: refact

#179 Refact/form useMutation 및 uesEffect로 스피너 제어하던 부분을 수정
  src/app/form/(form)/QnaForm.tsx
  src/app/form/(form)/ReviewForm.tsx
  src/app/form/page.tsx
  src/hook/useImageInput.ts
  src/service/table/qna.ts
  src/service/table/review.ts
Labels: fix, refact

#181 [refact/font] 폰트 최적화
  src/app/styles/fonts/PretendardVariable-ko.woff2
  src/app/styles/fonts/PretendardVariable.woff2
  src/app/styles/fonts/REM-VariableFont_wght.ttf
  src/app/styles/fonts/fonts.ts
Labels: refact, style

#182 Refact/form pulse안나오던 버그 수정
  src/app/api/revalidate/product/[productId]/qna/route.ts
  src/app/api/revalidate/product/[productId]/review/route.ts
  src/app/customer/page.tsx
  src/app/form/(form)/QnaForm.tsx
  src/app/form/(form)/ReviewForm.tsx
  src/app/form/page.tsx
  src/app/product/[productId]/(article)/Qna.tsx
  src/app/product/[productId]/(article)/Review.tsx
  src/app/product/[productId]/Info.tsx
  src/components/Pagination.tsx
  src/components/review/ReviewBtnGroup.tsx
Labels: fix, refact

#180 [feat/admin_page] admin page layout 구성 & side navigation bar 컴포넌트 제작
  src/app/admin/layout.tsx
  src/app/admin/page.tsx
  src/app/admin/product/addProduct/page.tsx
  src/app/admin/product/page.tsx
  src/app/admin/store/page.tsx
  src/components/admin/aside/NavigationBar.tsx
  src/components/admin/aside/SideTab.tsx
  src/data/sideTab.json
Labels: feat, fix, style

#186 Refact/payment 최적화(짜잘한)
  src/app/payment/[userId]/page.tsx
  src/app/users/[userId]/UserInfoSection.tsx
Labels: fix, refact

#187 fix:버튼 사이즈 누락 수정
  src/app/auth/SignIn.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/product/[productId]/(article)/Qna.tsx
  src/components/Banner.tsx
  src/components/Card.tsx
  src/components/CustomLink.tsx
  src/components/Pagination.tsx
  src/components/Tab.tsx
  src/components/auth/AuthBtn.tsx
  src/components/category/HeadCategory.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/HeaderCart.tsx
  src/components/layout/PageBreadCrumb.tsx
  src/components/layout/PageControlBtnGroup.tsx
  src/components/layout/mobile/MobileHeader.tsx
  src/components/review/ReviewBtnGroup.tsx
Labels: fix

#189 [ feat/admin_product] admin product 페이지 제작
  src/app/admin/layout.tsx
  src/app/admin/product/addProduct/page.tsx
  src/app/admin/product/page.tsx
  src/app/api/admin/product/[productId]/route.ts
  src/app/api/admin/product/route.ts
  src/data/sideTab.json
  src/service/table/product.ts
Labels: feat, style

#188 [feat/adminReview] 관리자 리뷰 관리 페이지
  src/app/admin/review/AdminReview.tsx
  src/app/admin/review/ReviewItem.tsx
  src/app/admin/review/ReviewList.tsx
  src/app/admin/review/SelectCategory.tsx
  src/app/admin/review/SelectOrder.tsx
  src/app/admin/review/page.tsx
  src/app/api/admin/review/[reviewId]/route.ts
  src/app/api/admin/review/route.ts
  src/app/form/(form)/ReviewForm.tsx
  src/components/Pagination.tsx
  src/components/category/HeadCategory.tsx
  src/data/sideTab.json
  src/service/table/review.ts
  src/types/api.ts
  src/types/db.ts
  src/types/supabase.ts
Labels: feat, fix, style

#191 [feat/admin_layout] layout height 수정
  src/app/admin/layout.tsx
  src/components/admin/aside/NavigationBar.tsx
Labels: style

#192 [feat/admin_product] admin product page url 수정
  src/app/admin/product/addProduct/page.tsx
  src/app/admin/product/page.tsx
  src/data/sideTab.json
Labels: fix

#195 [feat/style]: 살짝 수정 (#174)
  src/app/admin/review/AdminReview.tsx
  src/app/admin/review/ReviewList.tsx
  src/app/admin/review/SelectCategory.tsx
  src/app/admin/review/SelectOrder.tsx
Labels: style

#196 [fix.middleware] 수정
  src/app/users/[userId]/page.tsx
  src/middleware.ts
Labels: fix

#201 Refact/finish 파일 정리 및 lodash제거
  package-lock.json
  package.json
  src/app/admin/qna/Answer.tsx
  src/app/admin/qna/Filter.tsx
  src/app/admin/qna/QnaCard.tsx
  src/app/admin/qna/page.tsx
  src/app/api/revalidate/product/[productId]/qna/route.ts
  src/app/api/revalidate/product/[productId]/review/route.ts
  src/app/form/(form)/QnaForm.tsx
  src/app/form/(form)/ReviewForm.tsx
  src/app/layout.tsx
  src/app/product/[productId]/(article)/Qna.tsx
  src/app/product/[productId]/(article)/Revalidate.tsx
  src/app/product/[productId]/(article)/Review.tsx
  src/app/product/[productId]/ControlForm.tsx
  src/app/product/[productId]/Info.tsx
  src/app/product/[productId]/StockTable.tsx
  src/components/auth/AuthBtn.tsx
  src/hook/useCustomMutation.ts
Labels: fix, refact

#203 [fix/mypage] 마이페이지 성능 및 리스트 정렬 적용
  src/app/api/user/[userId]/qna/route.ts
  src/app/api/user/[userId]/rent/route.ts
  src/app/api/user/[userId]/review/route.ts
  src/app/users/[userId]/page.tsx
Labels: fix, refact

#204 Refact/finish mobile 모바일 (캐러셀 배너)
  src/app/product/[productId]/Info.tsx
  src/components/Banner.tsx
  src/components/Carousel.tsx
  src/components/Tab.tsx
Labels: refact, style

#206 콘솔로그 삭제
  src/app/admin/promotion/(Banner)/BannerForm.tsx
  src/app/admin/promotion/(Carousel)/CarouselForm.tsx
  src/app/admin/rent/AdminRent.tsx
  src/app/admin/rent/RentList.tsx
  src/app/admin/rent/SelectStore.tsx
  src/app/api/admin/qna/[categoryId]/route.ts
  src/app/api/user/[userId]/review/[reviewId]/route.ts
  src/app/product/[productId]/ControlForm.tsx
  src/components/review/ReviewBtnGroup.tsx
Labels: chore

#207 [feat/admin_product] 상품 수정 기능 구현 (#183)
  src/app/admin/product/[productId]/page.tsx
  src/app/admin/product/page.tsx
Labels: feat

#208 fix : revalidate 시간 추가
  src/service/table/banner.ts
  src/service/table/carousel.ts
  src/service/table/category.ts
  src/service/table/product.ts
  src/service/table/qna.ts
  src/service/table/region.ts
  src/service/table/review.ts
Labels: fix

#209 Style/carousel useQuery staleTime추가 , 배너및 캐러셀 해상도 조절
  src/app/cart/CartItem.tsx
  src/app/category/[categoryId]/SelectOffice.tsx
  src/app/product/[productId]/(article)/Description.tsx
  src/app/product/[productId]/(article)/Qna.tsx
  src/app/product/[productId]/(article)/Review.tsx
  src/app/users/[userId]/(tabContent)/UserQnaList.tsx
  src/app/users/[userId]/(tabContent)/UserRentList.tsx
  src/app/users/[userId]/(tabContent)/UserReviewList.tsx
  src/components/Banner.tsx
  src/components/Carousel.tsx
  src/components/Revalidate.tsx
  src/components/review/ReviewItem.tsx
  src/middleware.ts
Labels: refact

#212 모바일 Ui변경 및 잡다한 오류수정
  src/app/cart/CartItem.tsx
  src/app/customer/page.tsx
  src/components/Accordion.tsx
  src/components/Banner.tsx
  src/components/Carousel.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Section.tsx
Labels: fix, refact

#213 Main에 병합
  src/app/cart/CartItem.tsx
  src/app/customer/page.tsx
  src/components/Accordion.tsx
  src/components/Banner.tsx
  src/components/Carousel.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Section.tsx
Labels: feat

#214 Fix/product 장바구니에 당일 날짜로 상품 담을 시 날짜가 전날로 저장되는 버그 수정
  src/app/product/[productId]/ControlForm.tsx
Labels: fix

#216 [fix/admin] 어드민 페이지 리뷰/렌트 관리 수정
  src/app/admin/rent/AdminRent.tsx
  src/app/admin/rent/SelectStore.tsx
  src/app/admin/review/AdminReview.tsx
  src/app/admin/review/SelectCategory.tsx
  src/components/admin/SelectOrder.tsx
Labels: fix

#215 [style/form] 스타일변경
  src/app/form/ProductInfo.tsx
  src/app/form/page.tsx
Labels: style

#220 [style/all]
  src/app/auth/[find]/layout.tsx
  src/components/Banner.tsx
  src/components/Carousel.tsx
  src/components/layout/Section.tsx
Labels: style

#219 [feat/admin] 관리자페이지 가기 버튼 추가
  src/components/auth/AuthBtn.tsx
Labels: feat

#221 [chore] 주석 제거
  src/app/admin/product/page.tsx
  src/app/api/user/[userId]/qna/route.ts
  src/app/form/page.tsx
  src/app/payment/[userId]/page.tsx
  src/components/layout/PageBreadCrumb.tsx
  src/utils/convertTime.ts
  src/utils/useStorage.ts
Labels: fix, chore

#223 CLS개선
  src/components/Card.tsx
  src/components/Carousel.tsx
  src/components/pulse/CardPulse.tsx
Labels: fix

#225 [fix/access] accessibility 개선
  src/app/admin/rent/SelectStore.tsx
  src/app/admin/review/SelectCategory.tsx
  src/components/admin/SelectOrder.tsx
  src/components/auth/AuthBtn.tsx
  src/components/category/HeadCategory.tsx
  src/components/layout/HeaderSearch.tsx
  src/components/layout/mobile/MobileSearch.tsx
Labels: fix

#228 [fix/breadcrumb] bread crumb 모바일 hidden 적용
  src/components/layout/PageBreadCrumb.tsx
Labels: fix

#227 [fix/header] header search CLS
  src/components/layout/HeaderSearch.tsx
Labels: fix, style

#229 [fix/mypage] 프로필 변경 시 이미지가 주소가 변경되는 문제 해결
  src/app/users/[userId]/EditUserInfo.tsx
Labels: fix

#230 [chore/og] open graph 이미지 수정
  public/images/opengraph-image.png
Labels: chore

#232 chore : kakao 가이드에 따른 og 이미지
  public/images/opengraph-image.png
  src/app/layout.tsx
Labels: chore

#239 [Hotfix] ISR 및 레이아웃 문제 수정
  src/app/users/[userId]/(tabContent)/UserQnaList.tsx
  src/service/table/product.ts
Labels: fix
